### ISSUE TITLE
Question -`parser: "@typescript-eslint/parser"` location 

### ISSUE THREAD

**Issue by jeniabrook** [JoshuaKGoldberg/linting-typescript-in-2023#6]
## Overview
Hi 👋, I have a question regarding the ESLint config.

You enabled typescript-eslint's rules in .ts and .tsx files via overrides, is there a particular reason why you did not include the parser - `@typescript-eslint/parser` there as well? Instead of having it in the main scope

```js
  overrides: [
    {
      //...
      files: ['**/*.{ts,tsx}'],
      parser: '@typescript-eslint/parser',
    },
  ],
```

Thanks!

**Comment by JoshuaKGoldberg** [comment]
Great question @jeniabrook! Your suggestion is accurate that that approach could work too - there's no need to use a TypeScript parser on `.js` files. I went with using `@typescript-eslint/parser` on all files to standardize all JS-like files using the same parser.

It's also possible to use typescript-eslint on JS files when `allowJs: true` is in TSConfigs. Some folks end up especially wanting that in mixed codebases.

Does that answer your question?

**Comment by jeniabrook** [comment]
@JoshuaKGoldberg Yep, thanks!
